#!/usr/bin/env bash
# This script configures a new Ubuntu machine by installing Nginx.
# Nginx is set to listen on port 80 and serves a page with a "Hello World" string.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Grant user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Hello World!"
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx to apply changes
sudo service nginx restart
