#!/usr/bin/env bash
# install load balancer

echo -e "Updating and performing some basic checks...\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

install haproxy

echo -e "\nSetting up some basic configurations.\n"

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 530918-web-01 54.90.45.16:80 check
    server 530918-web-02 100.26.222.243:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configuration set - Roundrobin On 530918-web-01 & 530918-web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
